# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('patient_name', models.CharField(help_text='Title Surname Firstname', max_length=100)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7)),
                ('date_of_birth', models.DateField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>', null=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('hmo', models.CharField(blank=True, help_text='Name of HMO(HMO ID Number)', max_length=200, verbose_name='HMO')),
            ],
            options={
                'ordering': ['card_number'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(help_text='Surname  Firstname  Othername', max_length=100, verbose_name='Patient Name')),
                ('date_of_visit', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>')),
                ('summary_of_visit', models.TextField(blank=True, max_length=500)),
                ('date_of_recall', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>')),
                ('reason_for_recall', models.TextField(blank=True, max_length=200)),
                ('recall_status', models.CharField(blank=True, choices=[('On Schedule', 'On Schedule'), ('A Reminder', 'A Reminder')], default='On Schedule', max_length=15)),
            ],
            options={
                'ordering': ['date_of_recall'],
            },
        ),
    ]
